version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet build
      - dotnet publish
artifacts:
  files:
    - deployment-app-csharp/basic-web-app/site/**/*
    - deployment-app-csharp/basic-web-app/aws-windows-deployment-manifest.json