version: 0.2

phases:

  build:
    commands:
      - dotnet build
      - dotnet publish
artifacts:
  files:
    - ./basic-web-app/site/**/*
    - ./basic-web-app/aws-windows-deployment-manifest.json
